# VacationPy
---

## Starter Code to Import Libraries and Load the Weather and Coordinates Data

In [27]:
# Dependencies and Setup
import hvplot.pandas
import pandas as pd
import requests
import os
import json

# Import API key
from api_keys import geoapify_key

In [28]:
# Load the CSV file created in Part 1 into a Pandas DataFrame
city_data_df = pd.read_csv("output_data/cities.csv")

# Display sample data
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,adamstown,-25.0660,-130.1015,62.82,54,97,20.33,PN,1724255873
1,1,anadyr,64.7500,177.4833,45.10,93,75,11.18,RU,1724255874
2,2,gouyave,12.1646,-61.7296,86.77,74,40,12.66,GD,1724255875
3,3,lishu,43.3047,124.3278,69.94,97,70,4.68,CN,1724255876
4,4,asau,46.4333,26.4000,81.39,29,50,2.44,RO,1724255877

---

### Step 1: Create a map that displays a point for every city in the `city_data_df` DataFrame. The size of the point should be the humidity in each city.

In [29]:
%%capture --no-display
# %pip install cartopy geoviews pyproj


# Configure the map plot
map_plot_1 = city_data_df.hvplot.points(
    "Lng",
    "Lat",
    geo = True,
    tiles = "OSM",
    frame_width = 800,
    frame_height = 600,
    size = "Humidity",
    color="City",
    alpha=.75
)

# Display the map
map_plot_1

:Overlay
   .WMTS.I   :WMTS   [Longitude,Latitude]
   .Points.I :Points   [Lng,Lat]   (City,Humidity)

### Step 2: Narrow down the `city_data_df` DataFrame to find your ideal weather condition

In [33]:
# Narrow down cities that fit criteria and drop any results with null values
weather_filtered_df = city_data_df.loc[(city_data_df["Max Temp"] < 75) & (city_data_df["Max Temp"] > 45) & (city_data_df["Wind Speed"] < 5) & (city_data_df["Cloudiness"] <10)]
# Drop any rows with null values
weather_filtered_df = weather_filtered_df.dropna()

# Display sample data
weather_filtered_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
56,56,beitbridge,-22.2167,30.0000,73.60,26,2,1.01,ZW,1724255940
116,116,chakari,-18.0629,29.8925,71.85,10,0,0.60,ZW,1724256014
117,117,petropavlovsk-kamchatsky,53.0452,158.6483,46.99,81,0,4.47,RU,1724255893
128,128,dauphin,51.1494,-100.0502,71.74,78,0,2.30,CA,1724256028
174,174,spring creek,40.7266,-115.5859,70.81,20,0,1.01,US,1724256083

### Step 3: Create a new DataFrame called `hotel_df`.

In [36]:
city = weather_filtered_df["City"]
country = weather_filtered_df["Country"]
lat = weather_filtered_df["Lat"]
lng = weather_filtered_df["Lng"]
humidity = weather_filtered_df["Humidity"]

# Create a new DataFrame with the selected columns
hotel_df = pd.DataFrame({
    "City": city,
    "Country": country,
    "Lat": lat,
    "Lng": lng,
    "Humidity": humidity
})

# Add an empty column, "Hotel Name," to the DataFrame so you can store the hotel found using the Geoapify API
hotel_df["Hotel Name"] = ""
hotel_df.head()

                         City Country      Lat       Lng  Humidity Hotel Name
56                 beitbridge      ZW -22.2167   30.0000        26
116                   chakari      ZW -18.0629   29.8925        10
117  petropavlovsk-kamchatsky      RU  53.0452  158.6483        81
128                   dauphin      CA  51.1494 -100.0502        78
174              spring creek      US  40.7266 -115.5859        20

### Step 4: For each city, use the Geoapify API to find the first hotel located within 10,000 metres of your coordinates.

In [39]:
# Set parameters to search for a hotel
radius = 10000
params = {
    "categories": "accommodation.hotel",
    "apiKey":geoapify_key
}

# Print a message to follow up the hotel search
print("Starting hotel search")

# Iterate through the hotel_df DataFrame
for index, row in hotel_df.iterrows():
    # get latitude, longitude from the DataFrame
    lat = row["Lat"]
    lon = row["Lng"]
    
    # Add filter and bias parameters with the current city's latitude and longitude to the params dictionary
    params["filter"] = f"circle:{lon},{lat},{radius}"
    params["bias"] = f"proximity:{lon},{lat}"
    
    # Set base URL
    base_url = "https://api.geoapify.com/v2/places"

    # Make and API request using the params dictionary
    name_address = requests.get(base_url, params=params)
    
    # Convert the API response to JSON format
    name_address = name_address.json()
    
    # Grab the first hotel from the results and store the name in the hotel_df DataFrame
    try:
        hotel_df.loc[index, "Hotel Name"] = name_address["features"][0]["properties"]["name"]
    except (KeyError, IndexError):
        # If no hotel is found, set the hotel name as "No hotel found".
        hotel_df.loc[index, "Hotel Name"] = "No hotel found"
        
    # Log the search results
    print(f"{hotel_df.loc[index, 'City']} - nearest hotel: {hotel_df.loc[index, 'Hotel Name']}")

# Display sample data
hotel_df

Starting hotel search
beitbridge - nearest hotel: Beitbridge Inn & Casino
chakari - nearest hotel: No hotel found
petropavlovsk-kamchatsky - nearest hotel: ООО Постоялый двор
dauphin - nearest hotel: No hotel found
spring creek - nearest hotel: No hotel found
patterson - nearest hotel: Hampton Inn & Suites
zhangjiakou - nearest hotel: 商务宾馆
murun-kuren - nearest hotel: No hotel found
iron river - nearest hotel: AmericInn
nevada - nearest hotel: No hotel found
ambatolampy - nearest hotel: Manja Ranch
newman - nearest hotel: No hotel found
mount isa - nearest hotel: Ibis Styles
fortuna - nearest hotel: Comfort Inn & Suites Redwood Country
kunming - nearest hotel: 震庄迎宾馆
ust-tsilma - nearest hotel: Прасковья
macomb - nearest hotel: No hotel found

,City,Country,Lat,Lng,Humidity,Hotel Name
56,beitbridge,ZW,-22.2167,30.0000,26,Beitbridge Inn & Casino
116,chakari,ZW,-18.0629,29.8925,10,No hotel found
117,petropavlovsk-kamchatsky,RU,53.0452,158.6483,81,ООО Постоялый двор
128,dauphin,CA,51.1494,-100.0502,78,No hotel found
174,spring creek,US,40.7266,-115.5859,20,No hotel found
238,patterson,US,37.4716,-121.1297,33,Hampton Inn & Suites
241,zhangjiakou,CN,40.8100,114.8794,79,商务宾馆
243,murun-kuren,MN,49.6342,100.1625,82,No hotel found
263,iron river,US,46.0927,-88.6423,41,AmericInn
329,nevada,US,39.2502,-116.7512,18,No hotel found
423,ambatolampy,MG,-19.3833,47.4167,90,Manja Ranch
464,newman,US,37.3138,-121.0208,54,No hotel found
466,mount isa,AU,-20.7333,139.5000,54,Ibis Styles
482,fortuna,US,40.5982,-124.1573,97,Comfort Inn & Suites Redwood Country
539,kunming,CN,25.0389,102.7183,86,震庄迎宾馆
546,ust-tsilma,RU,65.4410,52.1498,76,Прасковья
573,macomb,US,40.4592,-90.6718,73,No hotel found

### Step 5: Add the hotel name and the country as additional information in the hover message for each city in the map.

In [40]:
%%capture --no-display

# Configure the map plot
hotel_map=hotel_df.hvplot.scatter(
   "Lng", 
   "Lat", 
    color = "Hotel Name",
    alpha = 0.6,
    size = "Humidity",
    tiles = "OSM"
).opts(width = 800, height = 500, tools = ['hover'], title = "Hotel Map"

)

# Display the map
hotel_map

:Overlay
   .Tiles.I   :Tiles   [x,y]
   .Scatter.I :Scatter   [Lng]   (Lat,Hotel Name,Humidity)